<template>
  <div class="loadingio-spinner-gear-alk1mkyt2f">
    <div class="ldio-7i0x3udskq">
      <div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style scoped>
  @keyframes ldio-7i0x3udskq {
    0% {
      transform: rotate(0deg);
    }
    50% {
      transform: rotate(18deg);
    }
    100% {
      transform: rotate(36deg);
    }
  }
  .ldio-7i0x3udskq > div {
    transform-origin: 90.5px 90.5px;
    animation: ldio-7i0x3udskq 0.6134969325153374s infinite linear;
  }
  .ldio-7i0x3udskq > div div {
    position: absolute;
    width: 19px;
    height: 100px;
    background: #4c5cb3;
    left: 90.5px;
    top: 90.5px;
    transform: translate(-50%, -50%);
  }
  .ldio-7i0x3udskq > div div:nth-child(1) {
    width: 80px;
    height: 80px;
    border-radius: 50%;
  }
  .ldio-7i0x3udskq > div div:nth-child(7) {
    width: 30px;
    height: 30px;
    background: #f1f2f3;
    border-radius: 50%;
  }
  .ldio-7i0x3udskq > div div:nth-child(3) {
    transform: translate(-50%, -50%) rotate(36deg);
  }
  .ldio-7i0x3udskq > div div:nth-child(4) {
    transform: translate(-50%, -50%) rotate(72deg);
  }
  .ldio-7i0x3udskq > div div:nth-child(5) {
    transform: translate(-50%, -50%) rotate(108deg);
  }
  .ldio-7i0x3udskq > div div:nth-child(6) {
    transform: translate(-50%, -50%) rotate(144deg);
  }
  .loadingio-spinner-gear-alk1mkyt2f {
    width: 181px;
    height: 181px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
  }
  .ldio-7i0x3udskq {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-7i0x3udskq div {
    box-sizing: content-box;
  }

  /* generated by https://loading.io/ */
</style>
